/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhiteboardRouteImport } from './routes/whiteboard'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhiteboardIndexRouteImport } from './routes/whiteboard.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as WhiteboardBoardIdRouteImport } from './routes/whiteboard.$boardId'
import { Route as TasksListIdRouteImport } from './routes/tasks.$listId'
import { Route as ShopsProductsRouteImport } from './routes/shops.products'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as SettingsSegurancaRouteImport } from './routes/settings.seguranca'
import { Route as SettingsMembersRouteImport } from './routes/settings.members'
import { Route as SettingsGeralRouteImport } from './routes/settings.geral'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as FinanceTransactionsRouteImport } from './routes/finance.transactions'
import { Route as FinanceSettingsRouteImport } from './routes/finance.settings'
import { Route as FinanceImportRouteImport } from './routes/finance.import'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as ShopsSopsIndexRouteImport } from './routes/shops.sops.index'
import { Route as ShopsProductsIndexRouteImport } from './routes/shops.products.index'
import { Route as ShopsSopsProcessIdRouteImport } from './routes/shops.sops.$processId'
import { Route as ShopsProductsProductIdRouteImport } from './routes/shops.products.$productId'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicHooksTaskNotificationsRouteImport } from './routes/api/public/hooks/task-notifications'
import { Route as ApiPublicHooksSyncTrack123RouteImport } from './routes/api/public/hooks/sync-track123'
import { Route as ApiPublicHooksSyncShopOrdersRouteImport } from './routes/api/public/hooks/sync-shop-orders'
import { Route as ApiPublicHooksTrack123ShopIdSecretRouteImport } from './routes/api/public/hooks/track123.$shopId.$secret'
import { Route as ApiPublicHooksMailPollStatusInboxIdRouteImport } from './routes/api/public/hooks/mail.poll-status.$inboxId'
import { Route as ApiPublicHooksMailInboundInboxIdRouteImport } from './routes/api/public/hooks/mail.inbound.$inboxId'

const WhiteboardRoute = WhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardIndexRoute = WhiteboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhiteboardRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const WhiteboardBoardIdRoute = WhiteboardBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => WhiteboardRoute,
} as any)
const TasksListIdRoute = TasksListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => TasksRoute,
} as any)
const ShopsProductsRoute = ShopsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopsRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => ShopsRoute,
} as any)
const SettingsSegurancaRoute = SettingsSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeralRoute = SettingsGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceImportRoute = FinanceImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)
const ShopsSopsIndexRoute = ShopsSopsIndexRouteImport.update({
  id: '/sops/',
  path: '/sops/',
  getParentRoute: () => ShopsRoute,
} as any)
const ShopsProductsIndexRoute = ShopsProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsProductsRoute,
} as any)
const ShopsSopsProcessIdRoute = ShopsSopsProcessIdRouteImport.update({
  id: '/sops/$processId',
  path: '/sops/$processId',
  getParentRoute: () => ShopsRoute,
} as any)
const ShopsProductsProductIdRoute = ShopsProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopsProductsRoute,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTaskNotificationsRoute =
  ApiPublicHooksTaskNotificationsRouteImport.update({
    id: '/api/public/hooks/task-notifications',
    path: '/api/public/hooks/task-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncTrack123Route =
  ApiPublicHooksSyncTrack123RouteImport.update({
    id: '/api/public/hooks/sync-track123',
    path: '/api/public/hooks/sync-track123',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncShopOrdersRoute =
  ApiPublicHooksSyncShopOrdersRouteImport.update({
    id: '/api/public/hooks/sync-shop-orders',
    path: '/api/public/hooks/sync-shop-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrack123ShopIdSecretRoute =
  ApiPublicHooksTrack123ShopIdSecretRouteImport.update({
    id: '/api/public/hooks/track123/$shopId/$secret',
    path: '/api/public/hooks/track123/$shopId/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMailPollStatusInboxIdRoute =
  ApiPublicHooksMailPollStatusInboxIdRouteImport.update({
    id: '/api/public/hooks/mail/poll-status/$inboxId',
    path: '/api/public/hooks/mail/poll-status/$inboxId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMailInboundInboxIdRoute =
  ApiPublicHooksMailInboundInboxIdRouteImport.update({
    id: '/api/public/hooks/mail/inbound/$inboxId',
    path: '/api/public/hooks/mail/inbound/$inboxId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRouteWithChildren
  '/gratitude': typeof GratitudeRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/shops': typeof ShopsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteWithChildren
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/import': typeof FinanceImportRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/geral': typeof SettingsGeralRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/seguranca': typeof SettingsSegurancaRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops/products': typeof ShopsProductsRouteWithChildren
  '/tasks/$listId': typeof TasksListIdRoute
  '/whiteboard/$boardId': typeof WhiteboardBoardIdRoute
  '/finance/': typeof FinanceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/shops/products/$productId': typeof ShopsProductsProductIdRoute
  '/shops/sops/$processId': typeof ShopsSopsProcessIdRoute
  '/shops/products/': typeof ShopsProductsIndexRoute
  '/shops/sops/': typeof ShopsSopsIndexRoute
  '/api/public/hooks/sync-shop-orders': typeof ApiPublicHooksSyncShopOrdersRoute
  '/api/public/hooks/sync-track123': typeof ApiPublicHooksSyncTrack123Route
  '/api/public/hooks/task-notifications': typeof ApiPublicHooksTaskNotificationsRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/hooks/mail/inbound/$inboxId': typeof ApiPublicHooksMailInboundInboxIdRoute
  '/api/public/hooks/mail/poll-status/$inboxId': typeof ApiPublicHooksMailPollStatusInboxIdRoute
  '/api/public/hooks/track123/$shopId/$secret': typeof ApiPublicHooksTrack123ShopIdSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/gratitude': typeof GratitudeRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/import': typeof FinanceImportRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/geral': typeof SettingsGeralRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/seguranca': typeof SettingsSegurancaRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/tasks/$listId': typeof TasksListIdRoute
  '/whiteboard/$boardId': typeof WhiteboardBoardIdRoute
  '/finance': typeof FinanceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/whiteboard': typeof WhiteboardIndexRoute
  '/shops/products/$productId': typeof ShopsProductsProductIdRoute
  '/shops/sops/$processId': typeof ShopsSopsProcessIdRoute
  '/shops/products': typeof ShopsProductsIndexRoute
  '/shops/sops': typeof ShopsSopsIndexRoute
  '/api/public/hooks/sync-shop-orders': typeof ApiPublicHooksSyncShopOrdersRoute
  '/api/public/hooks/sync-track123': typeof ApiPublicHooksSyncTrack123Route
  '/api/public/hooks/task-notifications': typeof ApiPublicHooksTaskNotificationsRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/hooks/mail/inbound/$inboxId': typeof ApiPublicHooksMailInboundInboxIdRoute
  '/api/public/hooks/mail/poll-status/$inboxId': typeof ApiPublicHooksMailPollStatusInboxIdRoute
  '/api/public/hooks/track123/$shopId/$secret': typeof ApiPublicHooksTrack123ShopIdSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRouteWithChildren
  '/gratitude': typeof GratitudeRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/shops': typeof ShopsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteWithChildren
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/import': typeof FinanceImportRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/geral': typeof SettingsGeralRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/seguranca': typeof SettingsSegurancaRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops/products': typeof ShopsProductsRouteWithChildren
  '/tasks/$listId': typeof TasksListIdRoute
  '/whiteboard/$boardId': typeof WhiteboardBoardIdRoute
  '/finance/': typeof FinanceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/shops/products/$productId': typeof ShopsProductsProductIdRoute
  '/shops/sops/$processId': typeof ShopsSopsProcessIdRoute
  '/shops/products/': typeof ShopsProductsIndexRoute
  '/shops/sops/': typeof ShopsSopsIndexRoute
  '/api/public/hooks/sync-shop-orders': typeof ApiPublicHooksSyncShopOrdersRoute
  '/api/public/hooks/sync-track123': typeof ApiPublicHooksSyncTrack123Route
  '/api/public/hooks/task-notifications': typeof ApiPublicHooksTaskNotificationsRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/hooks/mail/inbound/$inboxId': typeof ApiPublicHooksMailInboundInboxIdRoute
  '/api/public/hooks/mail/poll-status/$inboxId': typeof ApiPublicHooksMailPollStatusInboxIdRoute
  '/api/public/hooks/track123/$shopId/$secret': typeof ApiPublicHooksTrack123ShopIdSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/finance'
    | '/gratitude'
    | '/habits'
    | '/login'
    | '/projects'
    | '/settings'
    | '/shops'
    | '/tasks'
    | '/whiteboard'
    | '/finance/accounts'
    | '/finance/import'
    | '/finance/settings'
    | '/finance/transactions'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/settings/geral'
    | '/settings/members'
    | '/settings/seguranca'
    | '/shops/$shopId'
    | '/shops/products'
    | '/tasks/$listId'
    | '/whiteboard/$boardId'
    | '/finance/'
    | '/projects/'
    | '/settings/'
    | '/shops/'
    | '/tasks/'
    | '/whiteboard/'
    | '/shops/products/$productId'
    | '/shops/sops/$processId'
    | '/shops/products/'
    | '/shops/sops/'
    | '/api/public/hooks/sync-shop-orders'
    | '/api/public/hooks/sync-track123'
    | '/api/public/hooks/task-notifications'
    | '/api/public/shopify/callback'
    | '/api/public/hooks/mail/inbound/$inboxId'
    | '/api/public/hooks/mail/poll-status/$inboxId'
    | '/api/public/hooks/track123/$shopId/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/gratitude'
    | '/habits'
    | '/login'
    | '/finance/accounts'
    | '/finance/import'
    | '/finance/settings'
    | '/finance/transactions'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/settings/geral'
    | '/settings/members'
    | '/settings/seguranca'
    | '/shops/$shopId'
    | '/tasks/$listId'
    | '/whiteboard/$boardId'
    | '/finance'
    | '/projects'
    | '/settings'
    | '/shops'
    | '/tasks'
    | '/whiteboard'
    | '/shops/products/$productId'
    | '/shops/sops/$processId'
    | '/shops/products'
    | '/shops/sops'
    | '/api/public/hooks/sync-shop-orders'
    | '/api/public/hooks/sync-track123'
    | '/api/public/hooks/task-notifications'
    | '/api/public/shopify/callback'
    | '/api/public/hooks/mail/inbound/$inboxId'
    | '/api/public/hooks/mail/poll-status/$inboxId'
    | '/api/public/hooks/track123/$shopId/$secret'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/finance'
    | '/gratitude'
    | '/habits'
    | '/login'
    | '/projects'
    | '/settings'
    | '/shops'
    | '/tasks'
    | '/whiteboard'
    | '/finance/accounts'
    | '/finance/import'
    | '/finance/settings'
    | '/finance/transactions'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/settings/geral'
    | '/settings/members'
    | '/settings/seguranca'
    | '/shops/$shopId'
    | '/shops/products'
    | '/tasks/$listId'
    | '/whiteboard/$boardId'
    | '/finance/'
    | '/projects/'
    | '/settings/'
    | '/shops/'
    | '/tasks/'
    | '/whiteboard/'
    | '/shops/products/$productId'
    | '/shops/sops/$processId'
    | '/shops/products/'
    | '/shops/sops/'
    | '/api/public/hooks/sync-shop-orders'
    | '/api/public/hooks/sync-track123'
    | '/api/public/hooks/task-notifications'
    | '/api/public/shopify/callback'
    | '/api/public/hooks/mail/inbound/$inboxId'
    | '/api/public/hooks/mail/poll-status/$inboxId'
    | '/api/public/hooks/track123/$shopId/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  GratitudeRoute: typeof GratitudeRoute
  HabitsRoute: typeof HabitsRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ShopsRoute: typeof ShopsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  WhiteboardRoute: typeof WhiteboardRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicHooksSyncShopOrdersRoute: typeof ApiPublicHooksSyncShopOrdersRoute
  ApiPublicHooksSyncTrack123Route: typeof ApiPublicHooksSyncTrack123Route
  ApiPublicHooksTaskNotificationsRoute: typeof ApiPublicHooksTaskNotificationsRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicHooksMailInboundInboxIdRoute: typeof ApiPublicHooksMailInboundInboxIdRoute
  ApiPublicHooksMailPollStatusInboxIdRoute: typeof ApiPublicHooksMailPollStatusInboxIdRoute
  ApiPublicHooksTrack123ShopIdSecretRoute: typeof ApiPublicHooksTrack123ShopIdSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard/': {
      id: '/whiteboard/'
      path: '/'
      fullPath: '/whiteboard/'
      preLoaderRoute: typeof WhiteboardIndexRouteImport
      parentRoute: typeof WhiteboardRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/shops/': {
      id: '/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/whiteboard/$boardId': {
      id: '/whiteboard/$boardId'
      path: '/$boardId'
      fullPath: '/whiteboard/$boardId'
      preLoaderRoute: typeof WhiteboardBoardIdRouteImport
      parentRoute: typeof WhiteboardRoute
    }
    '/tasks/$listId': {
      id: '/tasks/$listId'
      path: '/$listId'
      fullPath: '/tasks/$listId'
      preLoaderRoute: typeof TasksListIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/shops/products': {
      id: '/shops/products'
      path: '/products'
      fullPath: '/shops/products'
      preLoaderRoute: typeof ShopsProductsRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/settings/seguranca': {
      id: '/settings/seguranca'
      path: '/seguranca'
      fullPath: '/settings/seguranca'
      preLoaderRoute: typeof SettingsSegurancaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/geral': {
      id: '/settings/geral'
      path: '/geral'
      fullPath: '/settings/geral'
      preLoaderRoute: typeof SettingsGeralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/settings': {
      id: '/finance/settings'
      path: '/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/import': {
      id: '/finance/import'
      path: '/import'
      fullPath: '/finance/import'
      preLoaderRoute: typeof FinanceImportRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/shops/sops/': {
      id: '/shops/sops/'
      path: '/sops'
      fullPath: '/shops/sops/'
      preLoaderRoute: typeof ShopsSopsIndexRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/shops/products/': {
      id: '/shops/products/'
      path: '/'
      fullPath: '/shops/products/'
      preLoaderRoute: typeof ShopsProductsIndexRouteImport
      parentRoute: typeof ShopsProductsRoute
    }
    '/shops/sops/$processId': {
      id: '/shops/sops/$processId'
      path: '/sops/$processId'
      fullPath: '/shops/sops/$processId'
      preLoaderRoute: typeof ShopsSopsProcessIdRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/shops/products/$productId': {
      id: '/shops/products/$productId'
      path: '/$productId'
      fullPath: '/shops/products/$productId'
      preLoaderRoute: typeof ShopsProductsProductIdRouteImport
      parentRoute: typeof ShopsProductsRoute
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-notifications': {
      id: '/api/public/hooks/task-notifications'
      path: '/api/public/hooks/task-notifications'
      fullPath: '/api/public/hooks/task-notifications'
      preLoaderRoute: typeof ApiPublicHooksTaskNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-track123': {
      id: '/api/public/hooks/sync-track123'
      path: '/api/public/hooks/sync-track123'
      fullPath: '/api/public/hooks/sync-track123'
      preLoaderRoute: typeof ApiPublicHooksSyncTrack123RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-shop-orders': {
      id: '/api/public/hooks/sync-shop-orders'
      path: '/api/public/hooks/sync-shop-orders'
      fullPath: '/api/public/hooks/sync-shop-orders'
      preLoaderRoute: typeof ApiPublicHooksSyncShopOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/track123/$shopId/$secret': {
      id: '/api/public/hooks/track123/$shopId/$secret'
      path: '/api/public/hooks/track123/$shopId/$secret'
      fullPath: '/api/public/hooks/track123/$shopId/$secret'
      preLoaderRoute: typeof ApiPublicHooksTrack123ShopIdSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mail/poll-status/$inboxId': {
      id: '/api/public/hooks/mail/poll-status/$inboxId'
      path: '/api/public/hooks/mail/poll-status/$inboxId'
      fullPath: '/api/public/hooks/mail/poll-status/$inboxId'
      preLoaderRoute: typeof ApiPublicHooksMailPollStatusInboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mail/inbound/$inboxId': {
      id: '/api/public/hooks/mail/inbound/$inboxId'
      path: '/api/public/hooks/mail/inbound/$inboxId'
      fullPath: '/api/public/hooks/mail/inbound/$inboxId'
      preLoaderRoute: typeof ApiPublicHooksMailInboundInboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceImportRoute: typeof FinanceImportRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceImportRoute: FinanceImportRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsGeralRoute: typeof SettingsGeralRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsSegurancaRoute: typeof SettingsSegurancaRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGeralRoute: SettingsGeralRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsSegurancaRoute: SettingsSegurancaRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ShopsProductsRouteChildren {
  ShopsProductsProductIdRoute: typeof ShopsProductsProductIdRoute
  ShopsProductsIndexRoute: typeof ShopsProductsIndexRoute
}

const ShopsProductsRouteChildren: ShopsProductsRouteChildren = {
  ShopsProductsProductIdRoute: ShopsProductsProductIdRoute,
  ShopsProductsIndexRoute: ShopsProductsIndexRoute,
}

const ShopsProductsRouteWithChildren = ShopsProductsRoute._addFileChildren(
  ShopsProductsRouteChildren,
)

interface ShopsRouteChildren {
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  ShopsProductsRoute: typeof ShopsProductsRouteWithChildren
  ShopsIndexRoute: typeof ShopsIndexRoute
  ShopsSopsProcessIdRoute: typeof ShopsSopsProcessIdRoute
  ShopsSopsIndexRoute: typeof ShopsSopsIndexRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsShopIdRoute: ShopsShopIdRoute,
  ShopsProductsRoute: ShopsProductsRouteWithChildren,
  ShopsIndexRoute: ShopsIndexRoute,
  ShopsSopsProcessIdRoute: ShopsSopsProcessIdRoute,
  ShopsSopsIndexRoute: ShopsSopsIndexRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

interface TasksRouteChildren {
  TasksListIdRoute: typeof TasksListIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksListIdRoute: TasksListIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface WhiteboardRouteChildren {
  WhiteboardBoardIdRoute: typeof WhiteboardBoardIdRoute
  WhiteboardIndexRoute: typeof WhiteboardIndexRoute
}

const WhiteboardRouteChildren: WhiteboardRouteChildren = {
  WhiteboardBoardIdRoute: WhiteboardBoardIdRoute,
  WhiteboardIndexRoute: WhiteboardIndexRoute,
}

const WhiteboardRouteWithChildren = WhiteboardRoute._addFileChildren(
  WhiteboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRouteWithChildren,
  GratitudeRoute: GratitudeRoute,
  HabitsRoute: HabitsRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ShopsRoute: ShopsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  WhiteboardRoute: WhiteboardRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicHooksSyncShopOrdersRoute: ApiPublicHooksSyncShopOrdersRoute,
  ApiPublicHooksSyncTrack123Route: ApiPublicHooksSyncTrack123Route,
  ApiPublicHooksTaskNotificationsRoute: ApiPublicHooksTaskNotificationsRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicHooksMailInboundInboxIdRoute: ApiPublicHooksMailInboundInboxIdRoute,
  ApiPublicHooksMailPollStatusInboxIdRoute:
    ApiPublicHooksMailPollStatusInboxIdRoute,
  ApiPublicHooksTrack123ShopIdSecretRoute:
    ApiPublicHooksTrack123ShopIdSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
